# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pems.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npems.proto\"\x83\x03\n\x04PeMS\x12\x0c\n\x04time\x18\x01 \x01(\t\x12\x12\n\nstation_id\x18\x02 \x01(\r\x12\x10\n\x08\x64istrict\x18\x03 \x01(\r\x12\x0f\n\x07\x66reeway\x18\x04 \x01(\r\x12\x11\n\tdirection\x18\x05 \x01(\t\x12\x11\n\tlane_type\x18\x06 \x01(\t\x12\x16\n\x0estation_length\x18\x07 \x01(\x02\x12\x0f\n\x07samples\x18\x08 \x01(\r\x12\x1b\n\x13percentage_observed\x18\t \x01(\r\x12\x12\n\ntotal_flow\x18\n \x01(\r\x12\x19\n\x11\x61verage_occupancy\x18\x0b \x01(\x02\x12\x15\n\raverage_speed\x18\x0c \x01(\x02\x12\x19\n\x05lanes\x18\r \x03(\x0b\x32\n.PeMS.Lane\x1ai\n\x04Lane\x12\x0f\n\x07samples\x18\x01 \x01(\r\x12\x0c\n\x04\x66low\x18\x02 \x01(\r\x12\x19\n\x11\x61verage_occupancy\x18\x03 \x01(\x02\x12\x15\n\raverage_speed\x18\x04 \x01(\x02\x12\x10\n\x08observed\x18\x05 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pems_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PEMS']._serialized_start=15
  _globals['_PEMS']._serialized_end=402
  _globals['_PEMS_LANE']._serialized_start=297
  _globals['_PEMS_LANE']._serialized_end=402
# @@protoc_insertion_point(module_scope)
